---
language: python
services: docker

env:
  matrix:
    # Test installing packages
    - MOLECULE_DISTRO: centos7
      MOLECULE_PLAYBOOK: playbook.yml
    - MOLECULE_DISTRO: ubuntu1804
      MOLECULE_PLAYBOOK: playbook.yml
    # Test CentOS specific tasks
    - MOLECULE_DISTRO: centos7
      MOLECULE_PLAYBOOK: playbook-centos.yml
    # Test CentOS specific tasks
    - MOLECULE_DISTRO: ubuntu1804
      MOLECULE_PLAYBOOK: playbook-ubuntu.yml

install:
  # Install test dependencies.
  - pip install molecule docker

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
