---
- name: Install yum repositories
  yum_repository:
    # Required
    name: "{{ item.name }}"
    state: "{{ item.state | default(yum_repository_state) }}"
    baseurl: "{{ item.baseurl }}"
    description: "{{ item.description }}"
    # Optional
    async: "{{ item.async | default(omit) }}"
    attributes: "{{ item.attributes | default(omit) }}"
    bandwidth: "{{ item.bandwidth | default(omit) }}"
    cost: "{{ item.cost | default(omit) }}"
    deltarpm_metadata_percentage: "{{ item.deltarpm_metadata_percentage | default(omit) }}"
    deltarpm_percentage: "{{ item.deltarpm_percentage | default(omit) }}"
    enabled: "{{ item.enabled | default(omit) }}"
    enablegroups: "{{ item.enablegroups | default(omit) }}"
    exclude: "{{ item.exclude | default(omit) }}"
    failovermethod: "{{ item.failovermethod | default(omit) }}"
    file: "{{ item.file | default(omit) }}"
    gpgcakey: "{{ item.gpgcakey | default(omit) }}"
    gpgcheck: "{{ item.gpgcheck | default(omit) }}"
    gpgkey: "{{ item.gpgkey | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    http_caching: "{{ item.http_caching | default(omit) }}"
    include: "{{ item.include | default(omit) }}"
    includepkgs: "{{ item.includepkgs | default(omit) }}"
    ip_resolve: "{{ item.ip_resolve | default(omit) }}"
    keepalive: "{{ item.keepalive | default(omit) }}"
    keepcache: "{{ item.keepcache | default(omit) }}"
    metadata_expire: "{{ item.metadata_expire | default(omit) }}"
    metadata_expire_filter: "{{ item.metadata_expire_filter | default(omit) }}"
    metalink: "{{ item.metalink | default(omit) }}"
    mirrorlist: "{{ item.mirrorlist | default(omit) }}"
    mirrorlist_expire: "{{ item.mirrorlist_expire | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    params: "{{ item.params | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    priority: "{{ item.priority | default(omit) }}"
    protect: "{{ item.protect | default(omit) }}"
    proxy: "{{ item.proxy | default(omit) }}"
    proxy_password: "{{ item.proxy_password | default(omit) }}"
    proxy_username: "{{ item.proxy_username | default(omit) }}"
    repo_gpgcheck: "{{ item.repo_gpgcheck | default(omit) }}"
    reposdir: "{{ item.reposdir | default(omit) }}"
    retries: "{{ item.retries | default(omit) }}"
    s3_enabled: "{{ item.s3_enabled | default(omit) }}"
    selevel: "{{ item.selevel | default(omit) }}"
    serole: "{{ item.serole | default(omit) }}"
    setype: "{{ item.setype | default(omit) }}"
    seuser: "{{ item.seuser | default(omit) }}"
    skip_if_unavailable: "{{ item.skip_if_unavailable | default(omit) }}"
    ssl_check_cert_permissions: "{{ item.ssl_check_cert_permissions | default(omit) }}"
    sslcacert: "{{ item.sslcacert | default(omit) }}"
    sslclientcert: "{{ item.sslclientcert | default(omit) }}"
    sslclientkey: "{{ item.sslclientkey | default(omit) }}"
    sslverify: "{{ item.sslverify | default(omit) }}"
    throttle: "{{ item.throttle | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
    ui_repoid_vars: "{{ item.ui_repoid_vars | default(omit) }}"
    unsafe_writes: "{{ item.unsafe_writes | default(omit) }}"
    username: "{{ item.username | default(omit) }}"
  with_items: "{{ yum_repository }}"