---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -c molecule/yaml-lint.yml .
  ansible-lint -c molecule/ansible-lint.yml .
  flake8
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-rockylinux10}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    user: root
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_user: root
        ansible_become: false
  config_options:
    defaults:
      ALLOW_BROKEN_CONDITIONALS: true
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
  log: true
  options:
    vvv: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
scenario:
  name: default
verifier:
  name: ansible
