---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Test if htop was installed
      shell: htop -h
      register: htop
      changed_when: "htop.rc != 0"
      failed_when: "htop.rc != 0"

    - name: Test if rpmlint was installed
      shell: rpmlint -h
      register: rpm
      changed_when: "rpm.rc != 0"
      failed_when: "rpm.rc != 0"
      when: ansible_os_family == "RedHat"

    - name: Test if apt-clone was installed
      shell: apt-clone -h
      register: apt
      changed_when: "apt.rc != 0"
      failed_when: "apt.rc != 0"
      when: ansible_os_family == "Debian"
